#161966872 Implement User Login Feature
andela/ah-infinity-stones-frontend pull request #11
Opened 2019-01-17 12:04 UTC by ThaDeveloper

[![Build Status](https://travis-ci.org/andela/ah-infinity-stones-frontend.svg?branch=ch-setup-redux-161966863)](https://travis-ci.org/andela/ah-infinity-stones-frontend)
#### What does this PR do?
- Implement user login

#### Description of Task to be completed?
- create and style login component
- connect redux with async requests
- validate user inputs
- write tests

#### How should this be manually tested?
1. `$ git clone -b ft-user-login-16196687 https://github.com/andela/ah-infinity-stones-frontend.git`  and `$ cd ah-infinity-stones-frontend`
2. Install the dependencies - `$ npm install`
3. Start the app by running `$ npm start` - This will run the app in the development mode.  Open http://localhost:3000/login  to view it in the browser.
The page will reload if you make edits. 	You will also see any lint errors in the console.
4. Test the app by running `$ npm test` - This will Launch the test runner in the interactive watch mode.

#### What are the relevant pivotal tracker stories?
[#161966872](hhttps://www.pivotaltracker.com/story/show/161966872)

#### Screenshots
<img width="657" alt="screenshot 2019-01-17 at 14 59 32" src="https://user-images.githubusercontent.com/12385482/51317409-8f068180-1a68-11e9-88b6-faee7a06313f.png">
<img width="661" alt="screenshot 2019-01-17 at 14 57 19" src="https://user-images.githubusercontent.com/12385482/51317423-988fe980-1a68-11e9-93b6-96cc36743a98.png">
<img width="659" alt="screenshot 2019-01-17 at 14 58 42" src="https://user-images.githubusercontent.com/12385482/51317435-9d549d80-1a68-11e9-96f3-90514e02995b.png">

2019-01-18 08:57 UTC, kamyaD requested changes
The code looks clean, However, there are some changes raised by Hound that needs fixing.

2019-01-18 09:02 UTC, ThaDeveloper commented
> The code looks clean, However, there are some changes raised by Hound that needs fixing.

I have resolved all the critical ones, the few remaining are for adding docs to the code which I have done only that the violations haven't updated

2019-01-21 08:17 UTC, PromasterGuru approved these changes
Good Job

2019-01-21 08:46 UTC, kamyaD approved these changes

2019-01-21 13:45 UTC, merged