#161966863 Install and Setup Redux
andela/ah-infinity-stones-frontend pull request #2
Opened 2019-01-08 07:54 UTC by ThaDeveloper

#### What does this PR do?
- Setup Redux

#### Description of Task to be completed?
- Install redux, react-redux and redux-saga
- Create appropriate redux folder structure

#### How should this be manually tested?
1. `$ git clone -b ch-setup-redux-161966863 https://github.com/andela/ah-infinity-stones-frontend.git`  and `$ cd ah-infinity-stones-frontend`
2. Start the app by running `$ npm start` - This will run the app in the development mode.  Open http://localhost:3000 to view it in the browser.
The page will reload if you make edits. 	You will also see any lint errors in the console.
3. Test the app by running `$ npm test` - This will Launch the test runner in the interactive watch mode.

#### What are the relevant pivotal tracker stories?
[#161966863](https://www.pivotaltracker.com/story/show/161966863)

#### Screenshots
<img width="696" alt="screenshot 2019-01-08 at 10 51 53" src="https://user-images.githubusercontent.com/12385482/50817004-7a710d80-1333-11e9-92b7-184fcf7a6a2e.png">

2019-01-08 08:06 UTC, rkemmy commented
@ThaDeveloper please include a screenshot of package.json so that we can see the dependencies installed

2019-01-08 08:07 UTC, kamyaD commented
@ThaDeveloper this looks great.

2019-01-08 08:08 UTC, PromasterGuru commented
Good job @ThaDeveloper, it would also be advisable to add the container folder in the structure.

2019-01-08 08:17 UTC, ThaDeveloper commented
> @ThaDeveloper please include a screenshot of package.json so that we can see the dependencies installed. Also the reducers/index.js should have a trailing line. ESLint has flagged that. Great work

Eslint has been solved, for the dependencies, I bet it's better to check the files changed for a cleaner precise PR with a limited amount of screenshots.

2019-01-08 08:25 UTC, leonardnjura reviewed
Nice initial setup @ThaDeveloper  We need this for a real world or large app

2019-01-08 08:30 UTC, ThaDeveloper commented
> Good job @ThaDeveloper, it would also be advisable to add the container folder in the structure.

I don't think we need a container folder, based on what I know a container is simply a smart component, it's not independent of the component. @johnmutuma5  can add more light to this.

2019-01-08 08:41 UTC, codeplus254 commented
Great work! Everything is running without errors

2019-01-08 08:45 UTC, codeplus254 approved these changes
Looks great. Just ran it without errors

2019-01-08 09:36 UTC, PromasterGuru approved these changes

2019-01-08 14:35 UTC, johnmutuma5 requested changes
Justin please set an appropriate badge on the PR and check out [this comment](https://www.pivotaltracker.com/story/show/161966863/comments/198193524):

2019-01-09 11:38 UTC, ThaDeveloper commented
@johnmutuma5 This has been done, thanks

2019-01-09 12:52 UTC, kamyaD commented
@ThaDeveloper Good effort, however, please check  on Travis, it seems it's not passing.

2019-01-09 13:04 UTC, ThaDeveloper commented
> @ThaDeveloper Good effort, however, please check on Travis, it seems it's not passing.

This has been fixed, the fail was being caused by a failing test caused by the `__snapshots__`  which was supposed to be git ignored.

2019-01-09 13:05 UTC, kamyaD approved these changes
Thanks for fixing travis

2019-01-09 16:11 UTC, johnmutuma5 requested changes
Great work on the set up. Wonderful progress in such a short span of time @ThaDeveloper, I have left some reviews.

2019-01-09 16:11 UTC, johnmutuma5 commented on package.json
> +    "redux-devtools-extension": "^2.13.7",
@ThaDeveloper, this seems like it should be a devDependency not for production environment. 🤔

2019-01-09 16:11 UTC, johnmutuma5 commented on src/components/Articles/Articles.jsx
> +export default connect(mapStateToProps, mapDispatchToProps)(Articles);
@ThaDeveloper, nice work on this redux store connection. We can improve it by just passing the `actionCreators` object in the place of `mapDispatchToProps` and redux is going to call the `bindActionCreators` function for us internally.

```js
    // ...
    const actionCreators = { requestIncrement };
    export default connect(mapStateToProps, actionCreators)(Articles); // 🙂
```

2019-01-09 16:11 UTC, johnmutuma5 commented on src/redux/store.js
> +import { applyMiddleware, createStore, compose } from 'redux';
@ThaDeveloper, great work on this file. 👏

2019-01-09 16:11 UTC, johnmutuma5 commented on src/redux/sagas/rootSaga.js
> +import { put, takeLatest } from "redux-saga/effects";
This file is not really the rootSaga, it is probably the `incrementSaga.js` as it contain the `incrementSaga` and the `incrementRequestWatcher`. The watcher to listen for the `REQUEST_INCREMENT` action and the `incrementSaga` to handle the action. 🤔 

The` rootSaga` on the other hand should be created separately(*probably like how you put the `rootReducer` in the `index.js` of its package*). The work of the `rootSaga` is to `yield all` the `action watchers`, like `incrementRequestWatcher`, in the application and it is what runs in `middleware.run(rootSaga)` as you did in `store.js`.

2019-01-09 16:11 UTC, johnmutuma5 commented on src/redux/sagas/rootSaga.js
> +function* increment(action) {
This is the `saga`. We should probably name it `incrementSaga` for more clarity. It acts as the slave that receives instructions from any `watcher` that has registered it.

2019-01-09 16:11 UTC, johnmutuma5 commented on src/redux/sagas/rootSaga.js
> +export default function* saga() {
This is the `watcher` which should be yielded amongst other `watchers` in the `rootSaga`, that we should create as pointed out earlier. It's work is to listen for `actions` once it catches an `action`, it instructs the slave `saga` it has registered in `takeLatest` below, in this case the `incrementSaga`, handing it the action for processing(*as you saw, the `incrementSaga` takes `action` as argument*).

I hope the flow is getting clearer.

2019-01-09 16:11 UTC, johnmutuma5 commented on src/redux/store.js
> +import saga from "./sagas/rootSaga";
Remember to update this import once you decide where to put the `rootSaga` (*or `allSagas` to be consistent with how you have named `allReducers`*) 🙂

2019-01-10 07:02 UTC, ThaDeveloper commented on src/redux/sagas/rootSaga.js
> +import { put, takeLatest } from "redux-saga/effects";
Sure,totally makes sense

2019-01-10 07:03 UTC, ThaDeveloper commented on src/redux/sagas/rootSaga.js
> +function* increment(action) {
Cool

2019-01-10 07:05 UTC, ThaDeveloper commented
@johnmutuma5 All the changes have been made, kindly have a look

2019-01-10 07:26 UTC, johnmutuma5 requested changes
@ThaDeveloper, this is incredible. Very good setup. Please respond to one more comment below and we'll be done with this one. Thanks.

2019-01-10 07:26 UTC, johnmutuma5 commented on src/redux/store.js
> +import rootSaga from "./sagas/rootSaga";
@ThaDeveloper, for consistency, I suggest we put the `rootSaga` in the `index.js` of the sagas like how we have done with the `allReducers`; unless you can foresee a problem with that.

2019-01-10 07:29 UTC, ThaDeveloper commented on src/redux/store.js
> +import rootSaga from "./sagas/rootSaga";
okay, no problem

2019-01-10 08:21 UTC, johnmutuma5 approved these changes
Great work. @ThaDeveloper

2019-01-10 08:22 UTC, merged